
<!-- Guidance  -->
<div class="container">
<!-- #content -->
<section id="content" role="main">
  <article id="post-6919" class="post-6919 st_kb type-st_kb status-publish hentry clearfix"> 
<!-- .entry-header -->
<div class="entry-header">  <h1 class="entry-title"> Fields and values</h1></div>
<!-- .entry-content -->
<div class="entry-content clearfix">
  <h3>Standard fields and values</h3>
<p><em style="color:red">*Note:&nbsp; M=Mandatory, O=Optional</em></p>
<table class="table">
<tbody>
<tr>
<td width="15%" valign="top"><b>Field</b></td>
<td width="8%" valign="top"><p align="center"><b>M/O</b></p></td>
<td width="39%" valign="top"><p><b>Description</b></p></td>
<td width="15%" valign="top"><p align="center"><b>Expected Value</b></p></td>
<td width="20%" valign="top"><p align="center"><b>Format</b></p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>product_id</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>Product Identifier for PAYDirect. </p></td>
<td width="15%" valign="top"><p align="center"><strong>&lt;to be provided&gt;</strong></p></td>
<td width="20%" valign="top"><p align="center">Numeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>amount</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>Transaction amount in small (kobo or cents)    denomination. E.g., 200000 for 2,000.00</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>currency</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>Currency of the transaction </p></td>
<td width="15%" valign="top"><p align="center">566 (For Naira)</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>site_redirect_url</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>URL of the page on your web site/portal    user is to be redirected to after payment. You may want to add encrypted    authentication information to allow a user renter the web site/portal    transparently without being challenged </p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>txn_ref</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>Transaction Reference Number. This Reference    Number must be generated by your web site/portal and a unique value must be    sent for each transaction</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>hash</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>A Hashed value    of selected combined parameters. See <a href="/docs/webpay/integration-overview#compute-hash">How to compute the request hash.</a></p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">date time</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>pay_item_id</strong></p></td>
<td width="8%" valign="top"><p align="center">M</p></td>
<td width="39%" valign="top"><p>PAYDirect Payment Item ID</p></td>
<td width="15%" valign="top"><p align="center"><strong>&lt;to be    provided&gt; </strong></p></td>
<td width="20%" valign="top"><p align="center">numeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>site_name</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Internet    site name of the web site/ portal from which http post is coming from. E.g. <a href="http://www.abc.com/">www.abc.com</a>.    This internet site name will be authenticated. </p></td>
<td width="15%" valign="top"><p align="center"><strong>&lt;to be    provided&gt; </strong></p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>cust_id</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Unique Customer Identification Number</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>cust_id_desc</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Customer Identification Number description. A    descriptive name/label for Customer Identification Number above.</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>cust_name</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Customer Name</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>cust_name_desc</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Customer Name Description. A descriptive    name/label for Customer Name above.</p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>pay_item_name</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>PAYDirect Payment Item Name</p></td>
<td width="15%" valign="top"><p align="center"><strong>&lt;</strong><strong>to be provided&gt; </strong></p></td>
<td width="20%" valign="top"><p align="center">alphanumeric</p></td>
</tr>
<tr>
<td width="15%" valign="top"><p><strong>local_date_time</strong></p></td>
<td width="8%" valign="top"><p align="center">O</p></td>
<td width="39%" valign="top"><p>Local    Transaction Date Time: DD-MMM-YY HH:MM:SS </p></td>
<td width="15%" valign="top"><p align="center">&lt;variable&gt;</p></td>
<td width="20%" valign="top"><p align="center">date time</p></td>
</tr>
</tbody>
</table>

<h3>Advanced fields and values</h3>

<table class="table">
  <tbody>
    <tr>
      <td width="20%" valign="top"><p><b>Field</b></p></td>
      <td width="30%" valign="top"><p><b>Description</b></p></td>
      <td width="20%" valign="top"><p><b>Expected Value</b></p></td>
      <td width="28%" valign="top"><p align="center"><b>Format</b></p></td>
    </tr>
    <tr>
      <td width="20%" valign="top"><p><strong>payment_params</strong></p></td>
      <td width="30%" valign="top"><p>For    miscellaneous payment parameters </p></td>
      <td width="20%" valign="top"><p>&lt;variable&gt;</p></td>
      <td width="28%" valign="top"><p align="center">alphanumeric</p></td>
    </tr>
    <tr>
      <td width="20%" valign="top"><p><strong>xml_data</strong></p></td>
      <td width="30%" valign="top"><p>Any other data    that needs to be sent will be packaged as xml and put in this field </p></td>
      <td width="20%" valign="top"><p>&lt;variable&gt;</p></td>
      <td width="28%" valign="top"><p align="center">xml</p></td>
    </tr>
  </tbody>
</table>

<h4>‘xml_data’  format</h4>
  <pre class="prettyprint">
    <span class="tag">&lt;payment_item_detail&gt;</span><span class="pln"></span><span class="tag">&lt;item_details</span><span class="pln"> </span><span class="atn">detail_ref</span><span class="pun">=</span><span class="atv">“XXXAFTXXX”</span><span class="pln"> </span><span class="atn">institution</span><span class="pun">=</span><span class="atv">“ABC”</span><span class="pln"> </span><span class="atn">sub_location</span><span class="pun">=</span><span class="atv">““location=““</span><span class="tag">&gt;</span><span class="pln"></span><span class="tag">&lt;item_detail</span><span class="pln"> </span><span class="atn">item_id</span><span class="pun">=</span><span class="atv">“1”</span><span class="pln"> </span><span class="atn">item_name</span><span class="pun">=</span><span class="atv">“Butter”</span><span class="pln"> </span><span class="atn">item_amt</span><span class="pun">=</span><span class="atv">“0000”</span><span class="pln"> </span><span class="atn">bank_id</span><span class="pun">=</span><span class="atv">“0”</span><span class="pln"> </span><span class="atn">acct_num</span><span class="pun">=</span><span class="atv">“435678”</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln"></span><span class="tag">&lt;item_detail</span><span class="pln"> </span><span class="atn">item_id</span><span class="pun">=</span><span class="atv">“2”</span><span class="pln"> </span><span class="atn">item_name</span><span class="pun">=</span><span class="atv">“Juice”</span><span class="pln"> </span><span class="atn">item_amt</span><span class="pun">=</span><span class="atv">“0000”</span><span class="pln"> </span><span class="atn">bank_id</span><span class="pun">=</span><span class="atv">“9”</span><span class="pln"> </span><span class="atn">acct_num</span><span class="pun">=</span><span class="atv">“6010153866”</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln"></span><span class="tag">&lt;/item_details&gt;</span><span class="pln"></span><span class="tag">&lt;/payment_item_detail&gt;</span>
  </pre>
<p style="color:red">The addition of the item_amt in the split data <strong>must</strong> be the equal to the amount<strong>-</strong>transaction  fee<br>
  Hence (item_amt+item_amt+…item_amt) = (amount-transaction fee). This  is to say that you would like to split a specified amount after the transaction  fee has been deducted. </p>
<h4>Sample request</h4>
  <pre class="prettyprint">
    <span class="tag">&lt;form</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"form1"</span><span class="pln"> </span><span class="atn">action</span><span class="pun">=</span><span class="atv">"https://testwebpay.interswitchng.com/test_paydirect/pay method="</span><span class="atn">post</span><span class="atv">"&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"product_id"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"XX"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"amount"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"XXXXXXX"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"currency"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"566"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"site_redirect_url"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"http://abc.com/new_page/getresponse.aspx?echo="</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"site_name"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"http://www.abc.com"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"cust_id"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"a"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"cust_id_desc"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"Value Name"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    &lt;input name="cust_name" type="hidden" value="Name </span><span class="tag">&lt;B&gt;</span><span class="pln">Surname</span><span class="tag">&lt;/B&gt;</span><span class="pln">" /&gt;    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"cust_name_desc"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"Full name"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"txn_ref"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">" XXXAFTXXX”"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"pay_item_id"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"XXXXX"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"pay_item_name"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"Name of Fees/Payment"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"local_date_time"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">""</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"hash"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"BB292DF9268F05CB9CBBC5E0C13CC1B13ACA34DC"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;input</span><span class="pln"> </span><span class="atn">name</span><span class="pun">=</span><span class="atv">"payment_params"</span><span class="pln"> </span><span class="atn">type</span><span class="pun">=</span><span class="atv">"hidden"</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"payment_split"</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    &lt;input name="xml_data" type="hidden" value='</span><span class="tag">&lt;payment_item_detail&gt;</span><span class="pln">    </span><span class="tag">&lt;item_details</span><span class="pln"> </span><span class="atn">detail_ref</span><span class="pun">=</span><span class="atv">“XXXAFTXXX”</span><span class="pln"> </span><span class="atn">institution</span><span class="pun">=</span><span class="atv">“ABC”</span><span class="pln"> </span><span class="atn">sub_location</span><span class="pun">=</span><span class="atv">““location=““</span><span class="tag">&gt;</span><span class="pln">    </span><span class="tag">&lt;item_detail</span><span class="pln"> </span><span class="atn">item_id</span><span class="pun">=</span><span class="atv">“1”</span><span class="pln"> </span><span class="atn">item_name</span><span class="pun">=</span><span class="atv">“Butter”</span><span class="pln"> </span><span class="atn">item_amt</span><span class="pun">=</span><span class="atv">“0000”</span><span class="pln"> </span><span class="atn">bank_id</span><span class="pun">=</span><span class="atv">“0”</span><span class="pln"> </span><span class="atn">acct_num</span><span class="pun">=</span><span class="atv">“435678”</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;item_detail</span><span class="pln"> </span><span class="atn">item_id</span><span class="pun">=</span><span class="atv">“2”</span><span class="pln"> </span><span class="atn">item_name</span><span class="pun">=</span><span class="atv">“Juice”</span><span class="pln"> </span><span class="atn">item_amt</span><span class="pun">=</span><span class="atv">“0000”</span><span class="pln"> </span><span class="atn">bank_id</span><span class="pun">=</span><span class="atv">“9”</span><span class="pln"> </span><span class="atn">acct_num</span><span class="pun">=</span><span class="atv">“6010153866”</span><span class="pln"> </span><span class="tag">/&gt;</span><span class="pln">    </span><span class="tag">&lt;/item_details&gt;</span><span class="pln">    </span><span class="tag">&lt;/payment_item_detail&gt;</span><span class="pln">' /&gt;    </span>
  </pre>
</div>
<!-- ./entry-content -->
</article>
</section>
<!-- #content -->
</div>